on:
  # Warning: using the pull_request_target event without the cautionary measures may allow
  # unauthorized GitHub users to open a “pwn request” and exfiltrate secrets.
  pull_request_target:
    types: [opened, synchronize, reopened]

name: SonarCloud Code Scan
jobs:
  # For monorepos, create one job per project and specify the directory
  sonarqube-src:
    environment: ${{ github.event_name == 'pull_request_target' &&
      github.event.pull_request.head.repo.full_name != github.repository && 'sonar-pr' || 'none' }}
    name: scan-synapse-react-client
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Disabling shallow clones is recommended for improving the relevancy of reporting
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: packages/synapse-react-client
          args: |
            '-Dsonar.pullrequest.key=${{ github.event.pull_request.number }}'
